### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mansabbloch** [WITPASS/WebApp#2]
## Beta-1
- [x] Docker Integration
- [x] [Admin] Single Page CRUD
- [x] [Public] Front-End Website Template
- [x] [API] Swagger API Explorer
- [x] [API] Add Generic API Controller
- [x] [Admin] Add Generic HTTP Service
- [ ] [API] Authentication Server
- [ ] Authorization Integration
- [x] [API] User API
- [ ] [Admin] User CRUD
- [x] [API] Branch API
- [ ] [Admin] Branch CRUD
- [ ] [Admin] User Account Management
- [ ] [Public] User Account Management
- [ ] [Admin] User Management
- [ ] [Admin] Branch Management
- [ ] [Admin] Dynamic Multilevel Menu
- [ ] [Public] Dynamic Multilevel Menu
